### ISSUE TITLE
How to clone into local environment? 

### ISSUE THREAD

**Issue by Heasummn** [crowdpublishtv/crowdpublishtv#54] opened 2015-09-24 00:59 UTC
I'm getting a multitude of errors involving aws error keys. I haven't dealt with aws, but believe that I can handle some of the issues regarding design and implementation in the app.

**Comment by crowdpublishtv** [comment] 2015-09-24 02:02
You'll have to comment out anything that requires aws or stripe keys. I'll work on making that easier to fork/clone tomorrow. However since you won't have those keys, that means you won't be able to use or test stripe on your local app.

**Comment by Heasummn** [comment] 2015-09-24 04:55
How would I get these keys without making accounts? Is there a way to cleanly remove all of this functionality because I don't want to deal with it?

**Comment by crowdpublishtv** [comment] 2015-09-26 23:54
Heasummn, I have updated files & instructions in README. I tried to figure out a way that would be easiest for people who would like to join the project. Full functionality won't be available since you don't have AWS or stripe keys. I'm not sure if you need Devise keys or not. Let me know if you run into obstacles & if you have any suggestions.

**Comment by wiafe** [comment] 2015-10-23 20:35
@crowdpublishtv So how do I start it up locally, would like to help on the styling side, see some issues I would like to help out with.

**Comment by crowdpublishtv** [comment] 2015-10-23 20:46
Hi Randy. Did you try the README instructions & get stuck? Please let me know if there is a specific issue you're having when following the README instructions.
I read up on recommended solutions for repos with secret keys & they recommended what I'm doing, which is to put in dummy key & alert contributors that they will need to get their own keys if they'd like to test for the functionality that requires those keys.

**Comment by wiafe** [comment] 2015-10-23 20:50
@crowdpublishtv I just did a pull-request that added 

    Then type
    >bin/rails server
    at the command line to start the server.

**Comment by crowdpublishtv** [comment] 2015-10-23 21:21
The README addition is great. There were also some changes to the gemfile & to schema.rb which I think are mostly innocuous (though I'll have to change things back to use postgresql in my local & development environment). I'll look at them over the weekend to make sure I don't have problems with them before I accept the pull.

How did you find this repo? Through railsgirlsdc? If not, please take a look at this http://www.meetup.com/railsgirlsdc/events/225927082/ It describes upcoming weekly online & in-person collaborative events to coordinate on this project.

**Comment by wiafe** [comment] 2015-10-23 21:51
@crowdpublishtv Those changes occurred when I was installed the application, that's why in the pull-request I said to remove those if you can. Did have to change the ruby version to match my systems version (might be a caveat you can add to the Doc).

I was just searching for beginner issues, want to get my feet wet in the open source with my front-end skills.

**Comment by crowdpublishtv** [comment] 2015-10-23 22:02
A great first crack. I'm thinking this is a good excuse for me to change to Ruby 2.0 - I'll look at the reqs for that upgrade over the weekend. If you find anything that might be a glitch caused by upgrading, let me know.

**Comment by wiafe** [comment] 2015-10-23 22:22
@crowdpublishtv Yeah for sure! Right now I'm working on the navbar(Once the user is logged in), fixed the margin issue it has, and I'm refactoring some of the code for you then I'll put in another PR for that.

**Comment by wiafe** [comment] 2015-10-23 22:28
@crowdpublishtv Yeah of course! is it possible to do `ruby: "latest"`, like you would for package.json? If that works you can probably apply `latest` to the dependencies.

Right now I'm working on the navbar on user's page(margin issues), and their sidebar.

**Comment by crowdpublishtv** [comment] 2015-10-27 01:35
Ok, I merged your changes... and upgraded to Ruby 2.2.3 since that's the latest. So far, I don't know of any effects on the app by doing so. You'll have to do a git pull, which means you might have to tweak some files or delete them altogether before you can pull my changes.

**Comment by wiafe** [comment] 2015-10-27 16:03
@crowdpublishtv Ok!

**Comment by wiafe** [comment] 2015-10-28 04:09
@crowdpublishtv    
    /Users/randy/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require':     cannot load such file -- bundler/setup (LoadError)
	from /Users/randy/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/randy/Desktop/PersonalSites/crowdpublishtv/config/boot.rb:6:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'

Error I just ran into, by chance do you know how to fix?

**Comment by wiafe** [comment] 2015-10-28 04:35
Well Solved that error, by updating Ruby and bundler. Now onto the new error!

    crowdpublishtv/config/initializers/carrierwave.rb:1:in `<top (required)>': uninitialized constant Excon (NameError)

**Comment by crowdpublishtv** [comment] 2015-10-28 11:07
Try commenting out the lines 
#Excon.defaults[:write_timeout] = 10000
#  Excon.defaults = Excon.defaults.merge(:write_timeout => 10.minutes.to_i)
and
#      :aws_access_key_id      => ENV['AWS_KEY'],    
#      :aws_secret_access_key  => ENV['AWS_SECRET_KEY'],  

in /config/initializers/carrierwave.rb - the email shows that you had an error with this file, not sure why it isn't mentioned in your comment above. This may not solve that error completely. The problem may also be that you do not have an aws key. If you want to use those features, you need to get your own aws key by signing up for amazon s3.

Check your gemfile to see what database you have listed locally. I have gem 'pg'. You probably don't have postgresql on your machine and will need to change it to gem 'sqlite3'.

**Comment by crowdpublishtv** [comment] 2015-10-28 11:08
Wow. Do not put spaces at the beginning of lines in github comments if you do not want to shout them in bold across the world

**Comment by wiafe** [comment] 2015-10-28 12:46
@crowdpublishtv Yeah that ended up working!

**Closed** 2017-12-01 04:46 UTC
